FROM node:20-alpine

RUN apk add --no-cache bash openssl libc6-compat

WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma ./prisma/
RUN npm install

RUN npx prisma generate

COPY . .

EXPOSE 3000 5555

CMD ["sh", "./scripts/docker-entrypoint-dev.sh"]