server {
    listen 443 ssl;
    server_name refunds.1337.ma;
    ssl_certificate /etc/ssl/1337.ma.crt;
    ssl_certificate_key /etc/ssl/1337.ma.key;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
    }
}

server {
    listen 80;
    server_name refunds.1337.ma;
    return 302 https://$server_name$request_uri;
}
